x = [
    [
        {
            'name': 'Large Appliances',
            'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/',
            'parent': 'Home Store'
        },
        {
            'name': 'Air Conditioners',
            'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/large-appliances-air-conditioners/',
            'parent': 'Home Store'
        },
        {
            'name': 'BBQ Grills',
            'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/large-appliances-bbq-grills/',
            'parent': 'Home Store'
        },
        {
            'name': 'Dishwashers',
            'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/dishwashers/',
            'parent': 'Home Store'
        },
        {
            'name': 'Fridges & Freezers',
            'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/fridges-freezers/',
            'parent': 'Home Store'}, {'name': 'Generators',
                                      'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/large-appliances-generators/',
                                      'parent': 'Home Store'}, {'name': 'Stoves Cooktops & Ovens',
                                                                'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/stoves-cooktops-ovens/',
                                                                'parent': 'Home Store'}, {'name': 'Washers & Dryers',
                                                                                          'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/large-appliances/washers-dryers/',
                                                                                          'parent': 'Home Store'},
        {'name': 'Small Appliances',
         'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/',
         'parent': 'Home Store'}, {'name': 'Blenders & Juicers',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-blenders/',
                                   'parent': 'Home Store'}, {'name': 'Choppers | Processors | Steamers',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-choppers-processors-steamers/',
                                                             'parent': 'Home Store'}, {'name': 'Fans',
                                                                                       'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-fans/',
                                                                                       'parent': 'Home Store'},
        {'name': 'Fryers',
         'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-fryers/',
         'parent': 'Home Store'}, {'name': 'Garment Steamers',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-garment-steamers/',
                                   'parent': 'Home Store'}, {'name': 'Irons',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-irons/',
                                                             'parent': 'Home Store'},
        {'name': 'Kettles & Coffee Makers',
         'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-kettles-coffee-makers/',
         'parent': 'Home Store'}, {'name': 'Microwaves',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-microwaves/',
                                   'parent': 'Home Store'}, {'name': 'Mixers',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-mixers/',
                                                             'parent': 'Home Store'}, {'name': 'Sewing Machines',
                                                                                       'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/sewing-machines/',
                                                                                       'parent': 'Home Store'},
        {'name': 'Toaster Ovens',
         'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-toaster-ovens/',
         'parent': 'Home Store'}, {'name': 'Other Small Appliances',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-other-small-appliances/',
                                   'parent': 'Home Store'}, {'name': 'Electronics',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/electronics/',
                                                             'parent': 'Home Store'}, {'name': 'Computers & Laptops',
                                                                                       'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/electronics/computers-laptops/',
                                                                                       'parent': 'Home Store'},
        {'name': 'Consumer Electronics',
         'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/electronics/consumer-electronics-electronics/',
         'parent': 'Home Store'}, {'name': 'Gaming Consoles',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/electronics/gaming-consoles/',
                                   'parent': 'Home Store'}, {'name': 'Tablets',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/electronics/electronics-tablets/',
                                                             'parent': 'Home Store'}, {'name': 'Televisions',
                                                                                       'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/electronics/electronics-televisions/',
                                                                                       'parent': 'Home Store'},
        {'name': 'Fitness', 'link': 'https://www.shopmassystoresbb.com/product-category/fitness/',
         'parent': 'Home Store'}, {'name': 'Home Essentials',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/home-essentials/',
                                   'parent': 'Home Store'}, {'name': 'Fans',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/small-appliances/small-appliances-fans/',
                                                             'parent': 'Home Store'}, {'name': 'Glassware',
                                                                                       'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/home-essentials/glassware/',
                                                                                       'parent': 'Home Store'},
        {'name': 'Kitchenware',
         'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/home-essentials/kitchenware/',
         'parent': 'Home Store'}, {'name': 'Personal Care',
                                   'link': 'https://www.shopmassystoresbb.com/product-category/home-appliances/personal-care/',
                                   'parent': 'Home Store'}
    ],
    [{'name': 'Baking Needs',
      'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/baking-needs-grocery-food/',
      'parent': 'Grocery'}, {'name': 'Bread/Cakes',
                             'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/bread-cakes-grocery-food/',
                             'parent': 'Grocery'},
     {'name': 'Canned Products', 'link': 'https://www.shopmassystoresbb.com/product-category/canned-products/',
      'parent': 'Grocery'}, {'name': 'Canned Vegetables',
                             'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/canned-vegetables-grocery-food/',
                             'parent': 'Grocery'}, {'name': 'Canned Meat',
                                                    'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/canned-meat-grocery-food/',
                                                    'parent': 'Grocery'},
     {'name': 'Cereal', 'link': 'https://www.shopmassystoresbb.com/?s=cereal&post_type=product', 'parent': 'Grocery'},
     {'name': 'Baby Cereal',
      'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/baby-cereal-grocery-food/',
      'parent': 'Grocery'}, {'name': 'Cold Cereal',
                             'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/cold-cereal-grocery-food/',
                             'parent': 'Grocery'}, {'name': 'Hot Cereal',
                                                    'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/hot-cereal-grocery-food/',
                                                    'parent': 'Grocery'}, {'name': 'Gravies/Sauces',
                                                                           'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/gravies-sauces-grocery-food/',
                                                                           'parent': 'Grocery'},
     {'name': 'Milk & Chilled Products',
      'link': 'https://www.shopmassystoresbb.com/product-category/milk-chilled-products-2/', 'parent': 'Grocery'},
     {'name': 'Pasta', 'link': 'https://www.shopmassystoresbb.com/product-category/pastas-grains-rice/',
      'parent': 'Grocery'}, {'name': 'Rice/Grains',
                             'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/rice-grains-grocery-food/',
                             'parent': 'Grocery'}, {'name': 'Seasoning/Spices/Stuffing',
                                                    'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/seasoning-spices-stuffing-grocery-food/',
                                                    'parent': 'Grocery'}, {'name': 'Sugar/Sweeteners',
                                                                           'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/sugar-sweeteners/',
                                                                           'parent': 'Grocery'}, {'name': 'Syrup/Honey',
                                                                                                  'link': 'https://www.shopmassystoresbb.com/product-category/grocery-food/syrup-honey-grocery-food/',
                                                                                                  'parent': 'Grocery'}],
    [{'name': 'Beer/Shandy', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/beer-shandy/',
      'parent': 'Wines & Spirits'},
     {'name': 'Wine', 'link': 'https://www.shopmassystoresbb.com/?s=wine&post_type=product',
      'parent': 'Wines & Spirits'},
     {'name': 'Red Wine', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/red-wine/',
      'parent': 'Wines & Spirits'},
     {'name': 'White Wine', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/white-wine/',
      'parent': 'Wines & Spirits'}, {'name': 'Rose/Blush Wine',
                                     'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/rose-blush-wine/',
                                     'parent': 'Wines & Spirits'}, {'name': 'Sparkling Wines/Champagnes',
                                                                    'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/sparkling-wines-champagnes/',
                                                                    'parent': 'Wines & Spirits'},
     {'name': 'Flavoured/Fortified Wine',
      'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/flavoured-fortified-wine/',
      'parent': 'Wines & Spirits'}, {'name': 'Non Alcoholic Wine',
                                     'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/non-alcoholic-wine-wines-spirits/',
                                     'parent': 'Wines & Spirits'},
     {'name': 'Drink Mixers', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/drink-mixers/',
      'parent': 'Wines & Spirits'},
     {'name': 'Liqueurs', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/liqueurs/',
      'parent': 'Wines & Spirits'}, {'name': 'Liquors',
                                     'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/liquors-wines-spirits/',
                                     'parent': 'Wines & Spirits'},
     {'name': 'Rum', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/rum/',
      'parent': 'Wines & Spirits'}, {'name': 'Brandy/Cognac',
                                     'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/brandy-cognac/',
                                     'parent': 'Wines & Spirits'},
     {'name': 'Vodka', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/vodka-wines-spirits/',
      'parent': 'Wines & Spirits'},
     {'name': 'Whiskey', 'link': 'https://www.shopmassystoresbb.com/product-category/wines-spirits/whiskey/',
      'parent': 'Wines & Spirits'}], [
        {'name': 'Baby Cereal', 'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/baby-cereal/',
         'parent': 'Baby Care'}, {'name': 'Baby Diapers',
                                  'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/baby-diapers-baby-care/',
                                  'parent': 'Baby Care'}, {'name': 'Baby Food/Juice',
                                                           'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/baby-food-juice/',
                                                           'parent': 'Baby Care'}, {'name': 'Baby Formula',
                                                                                    'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/baby-formula-baby-care/',
                                                                                    'parent': 'Baby Care'},
        {'name': 'Baby Needs',
         'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/baby-needs-baby-care/',
         'parent': 'Baby Care'}, {'name': 'Baby Wipes',
                                  'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/baby-wipes-baby-care/',
                                  'parent': 'Baby Care'},
        {'name': 'Milk', 'link': 'https://www.shopmassystoresbb.com/product-category/baby-care/milk-baby-care/',
         'parent': 'Baby Care'}], [
        {'name': 'Dried Fruits', 'link': 'https://www.shopmassystoresbb.com/product-category/produce/dried-fruits/',
         'parent': 'Produce'},
        {'name': 'Fruits', 'link': 'https://www.shopmassystoresbb.com/product-category/produce/fruits-produce/',
         'parent': 'Produce'}, {'name': 'Ground Provisions',
                                'link': 'https://www.shopmassystoresbb.com/product-category/produce/ground-provisions-produce/',
                                'parent': 'Produce'}, {'name': 'Produce Misc',
                                                       'link': 'https://www.shopmassystoresbb.com/product-category/produce/produce-misc-produce/',
                                                       'parent': 'Produce'},
        {'name': 'Vegetables', 'link': 'https://www.shopmassystoresbb.com/product-category/produce/vegetables-produce/',
         'parent': 'Produce'}], [{'name': 'Frozen Breakfast',
                                  'link': 'https://www.shopmassystoresbb.com/product-category/frozen-foods/frozen-breakfast-frozen-foods/',
                                  'parent': 'Frozen Food'}, {'name': 'Frozen Fruits & Vegetables',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/frozen-fruits-vegetables/',
                                                             'parent': 'Frozen Food'}, {'name': 'Frozen Meals',
                                                                                        'link': 'https://www.shopmassystoresbb.com/product-category/frozen-foods/frozen-meals-frozen-foods/',
                                                                                        'parent': 'Frozen Food'},
                                 {'name': 'Frozen Meat & Seafood',
                                  'link': 'https://www.shopmassystoresbb.com/product-category/frozen-meat-seafood/',
                                  'parent': 'Frozen Food'}, {'name': 'Frozen Misc',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/frozen-foods/frozen-misc-frozen-foods/',
                                                             'parent': 'Frozen Food'}, {'name': 'Frozen Prepared Foods',
                                                                                        'link': 'https://www.shopmassystoresbb.com/product-category/frozen-prepared-foods/',
                                                                                        'parent': 'Frozen Food'},
                                 {'name': 'Frozen Veg/Fruits',
                                  'link': 'https://www.shopmassystoresbb.com/product-category/frozen-foods/frozen-veg-fruits-frozen-foods/',
                                  'parent': 'Frozen Food'}, {'name': 'Icecream/Desserts',
                                                             'link': 'https://www.shopmassystoresbb.com/product-category/frozen-foods/icecream-desserts/',
                                                             'parent': 'Frozen Food'}], [
        {'name': 'Fresh Meat & Seafood',
         'link': 'https://www.shopmassystoresbb.com/product-category/fresh-meat-seafood/', 'parent': 'Meats & Seafood'},
        {'name': 'Frozen Meat & Seafood',
         'link': 'https://www.shopmassystoresbb.com/product-category/frozen-meat-seafood/',
         'parent': 'Meats & Seafood'}], [{'name': 'Cold/Flu',
                                          'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/cold-flu-pharmaceutical/',
                                          'parent': 'Health'}, {'name': 'Eye/Ear',
                                                                'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/eye-ear/',
                                                                'parent': 'Health'}, {'name': 'First Aid',
                                                                                      'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/first-aid-pharmacy/',
                                                                                      'parent': 'Health'},
                                         {'name': 'Medicated Skin Care',
                                          'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/medicated-skin-care-pharmacy/',
                                          'parent': 'Health'}, {'name': 'Other Health/Beauty Care',
                                                                'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/other-health-beauty-care-pharmacy/',
                                                                'parent': 'Health'}, {'name': 'Other Pharmaceutical',
                                                                                      'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/other-pharmaceutical/',
                                                                                      'parent': 'Health'},
                                         {'name': 'Pain Relief',
                                          'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/pain-relief/',
                                          'parent': 'Health'}, {'name': 'Pharmaceutical',
                                                                'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/pharmaceutical-pharmacy/',
                                                                'parent': 'Health'},
                                         {'name': 'Stomach/Digestive Health',
                                          'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/stomach-digestive-health/',
                                          'parent': 'Health'}, {'name': 'Vitamins/Supplement',
                                                                'link': 'https://www.shopmassystoresbb.com/product-category/pharmacy/vitamins-supplement/',
                                                                'parent': 'Health'}], [
        {'name': 'Beauty & Personal Care',
         'link': 'https://www.shopmassystoresbb.com/product-category/beauty-personal-care/', 'parent': 'Beauty'},
        {'name': 'Health & Beauty Care',
         'link': 'https://www.shopmassystoresbb.com/product-category/health-beauty-care/', 'parent': 'Beauty'}]]
